//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wab2018
{
    using System;
    using System.Collections.Generic;
    
    public partial class glo_specjalizacje
    {
        public int id_ { get; set; }
        public string nazwa { get; set; }
        public Nullable<int> grupa { get; set; }
    }
}
