//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wab2018
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_osoby
    {
        public long ident { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public string ulica { get; set; }
        public string kod_poczt { get; set; }
        public string miejscowosc { get; set; }
        public Nullable<System.DateTime> data_poczatkowa { get; set; }
        public Nullable<System.DateTime> data_koncowa { get; set; }
        public int id_kreatora { get; set; }
        public System.DateTime data_kreacji { get; set; }
        public long pesel { get; set; }
        public Nullable<int> czyus { get; set; }
        public Nullable<System.DateTime> d_usuniecia { get; set; }
        public Nullable<int> id_usuwajacego { get; set; }
        public string przyczyna_usuniecia { get; set; }
        public string tytul { get; set; }
        public Nullable<bool> czy_zaw { get; set; }
        public string tel1 { get; set; }
        public string tel2 { get; set; }
        public string email { get; set; }
        public string adr_kores { get; set; }
        public string kod_poczt_kor { get; set; }
        public string miejscowosc_kor { get; set; }
        public string uwagi { get; set; }
        public Nullable<System.DateTime> d_zawieszenia { get; set; }
        public string specjalizacjeWidok { get; set; }
        public string specjalizacja_opis { get; set; }
        public Nullable<int> typ { get; set; }
        public Nullable<System.DateTime> dataKoncaZawieszenia { get; set; }
    }
}
