//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wab2018
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_skargi
    {
        public int ident { get; set; }
        public string numer { get; set; }
        public Nullable<int> rok { get; set; }
        public Nullable<System.DateTime> dataWplywu { get; set; }
        public Nullable<System.DateTime> dataPisma { get; set; }
        public string Sygnatura { get; set; }
        public string wizytator { get; set; }
        public Nullable<int> zakreslono { get; set; }
        public Nullable<System.DateTime> dataZakreslenia { get; set; }
        public string uwagi { get; set; }
        public Nullable<int> czyus { get; set; }
        public Nullable<int> idBieglego { get; set; }
    }
}
